# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Error_decode\DataDefineManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataDefineManager(object):
    def setupUi(self, DataDefineManager):
        DataDefineManager.setObjectName("DataDefineManager")
        DataDefineManager.resize(599, 511)
        self.listWidget_data_define = QtWidgets.QListWidget(DataDefineManager)
        self.listWidget_data_define.setGeometry(QtCore.QRect(20, 30, 481, 401))
        self.listWidget_data_define.setObjectName("listWidget_data_define")
        self.pushButton_delete = QtWidgets.QPushButton(DataDefineManager)
        self.pushButton_delete.setGeometry(QtCore.QRect(30, 460, 101, 31))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.lineEdit = QtWidgets.QLineEdit(DataDefineManager)
        self.lineEdit.setGeometry(QtCore.QRect(150, 460, 341, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(DataDefineManager)
        QtCore.QMetaObject.connectSlotsByName(DataDefineManager)

    def retranslateUi(self, DataDefineManager):
        _translate = QtCore.QCoreApplication.translate
        DataDefineManager.setWindowTitle(_translate("DataDefineManager", "Form"))
        self.pushButton_delete.setText(_translate("DataDefineManager", "删除已选定义"))
