# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Error_decode\ErrorDecode.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrorDecode(object):
    def setupUi(self, ErrorDecode):
        ErrorDecode.setObjectName("ErrorDecode")
        ErrorDecode.resize(706, 516)
        self.pushButton = PushButton(ErrorDecode)
        self.pushButton.setGeometry(QtCore.QRect(380, 250, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_output = TextBrowser(ErrorDecode)
        self.textBrowser_output.setGeometry(QtCore.QRect(340, 10, 256, 192))
        self.textBrowser_output.setObjectName("textBrowser_output")
        self.lineEdit_input_num = LineEdit(ErrorDecode)
        self.lineEdit_input_num.setGeometry(QtCore.QRect(70, 240, 231, 31))
        self.lineEdit_input_num.setObjectName("lineEdit_input_num")
        self.textEdit_data_struct = TextEdit(ErrorDecode)
        self.textEdit_data_struct.setGeometry(QtCore.QRect(20, 20, 291, 191))
        self.textEdit_data_struct.setObjectName("textEdit_data_struct")

        self.retranslateUi(ErrorDecode)
        QtCore.QMetaObject.connectSlotsByName(ErrorDecode)

    def retranslateUi(self, ErrorDecode):
        _translate = QtCore.QCoreApplication.translate
        ErrorDecode.setWindowTitle(_translate("ErrorDecode", "Dialog"))
        self.pushButton.setText(_translate("ErrorDecode", "Shoooot!"))
from qfluentwidgets import LineEdit, PushButton, TextBrowser, TextEdit
