# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Error_decode\ErrorDecode.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrorDecode(object):
    def setupUi(self, ErrorDecode):
        ErrorDecode.setObjectName("ErrorDecode")
        ErrorDecode.resize(1000, 700)
        self.widget_table = TableWidget(ErrorDecode)
        self.widget_table.setGeometry(QtCore.QRect(490, 80, 501, 361))
        self.widget_table.setObjectName("widget_table")
        self.groupBox = QtWidgets.QGroupBox(ErrorDecode)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 461, 371))
        self.groupBox.setObjectName("groupBox")
        self.textEdit_data_struct = TextEdit(self.groupBox)
        self.textEdit_data_struct.setGeometry(QtCore.QRect(10, 20, 441, 341))
        self.textEdit_data_struct.setObjectName("textEdit_data_struct")
        self.groupBox_2 = QtWidgets.QGroupBox(ErrorDecode)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 550, 461, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textBrowser_output = TextBrowser(self.groupBox_2)
        self.textBrowser_output.setGeometry(QtCore.QRect(10, 20, 441, 61))
        self.textBrowser_output.setObjectName("textBrowser_output")
        self.groupBox_3 = QtWidgets.QGroupBox(ErrorDecode)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 460, 261, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_input_num = LineEdit(self.groupBox_3)
        self.lineEdit_input_num.setGeometry(QtCore.QRect(10, 30, 231, 31))
        self.lineEdit_input_num.setObjectName("lineEdit_input_num")
        self.groupBox_4 = QtWidgets.QGroupBox(ErrorDecode)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 460, 461, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_data_define_name = LineEdit(self.groupBox_4)
        self.lineEdit_data_define_name.setGeometry(QtCore.QRect(20, 30, 231, 31))
        self.lineEdit_data_define_name.setObjectName("lineEdit_data_define_name")
        self.pushButton = PushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(270, 30, 171, 31))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_data_define = ComboBox(ErrorDecode)
        self.comboBox_data_define.setGeometry(QtCore.QRect(130, 20, 201, 31))
        self.comboBox_data_define.setObjectName("comboBox_data_define")
        self.label = QtWidgets.QLabel(ErrorDecode)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 31))
        self.label.setObjectName("label")
        self.label_num = QtWidgets.QLabel(ErrorDecode)
        self.label_num.setGeometry(QtCore.QRect(510, 570, 461, 61))
        self.label_num.setObjectName("label_num")

        self.retranslateUi(ErrorDecode)
        QtCore.QMetaObject.connectSlotsByName(ErrorDecode)

    def retranslateUi(self, ErrorDecode):
        _translate = QtCore.QCoreApplication.translate
        ErrorDecode.setWindowTitle(_translate("ErrorDecode", "Dialog"))
        self.groupBox.setTitle(_translate("ErrorDecode", "变量定义"))
        self.groupBox_2.setTitle(_translate("ErrorDecode", "Log"))
        self.groupBox_3.setTitle(_translate("ErrorDecode", "待解析值"))
        self.groupBox_4.setTitle(_translate("ErrorDecode", "整体定义名"))
        self.pushButton.setText(_translate("ErrorDecode", "保存变量定义"))
        self.label.setText(_translate("ErrorDecode", "已保存定义"))
        self.label_num.setText(_translate("ErrorDecode", "DEC:0    HEX:0"))
from qfluentwidgets import ComboBox, LineEdit, PushButton, TableWidget, TextBrowser, TextEdit
