# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Error_decode\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButton = PushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = TextBroswer(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 10, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.plainTextEdit = PlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 220, 201, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = PlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(40, 260, 201, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
from qfluentwidgets import PlainTextEdit, PushButton, TextBroswer
